name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "TERM=linux" >> "$GITHUB_ENV"

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'
        check-latest: true

    - name: Build
      run: go build

    - name: Run Tests
      run: go test
